

name: Nigthly

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'
  



jobs:
  test:
    uses: MericFeyz/platform-launcher/.github/workflows/makefile.yaml@Iss_Nightly
  build:
    needs: test
    runs-on: ubuntu-20.04
    environment: Dockerhub
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_PREFIX: ${{ secrets.DOCKER_PREFIX }}
      PUSH_DRYRUN: "FALSE"
    steps:
      
      - name: Push images
        shell: bash
        run: |
          export TERM=vt100
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          pwd
          echo "Docker Prefix: $DOCKER_PREFIX"
          echo "Dryrun env: $PUSH_DRYRUN"
          
  
