

name: Nigthly

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *'
  



jobs:
  test:
    uses: MericFeyz/platform-launcher/.github/workflows/makefile.yaml@Iss_Nightly
    with:
      work: Nightly
          
  
