name: test

on:
  workflow_dispatch:
jobs:
  test:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    container:
      image: oisp/deployer:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Deploy Test
        run: |
          export TERM=vt100
          cd /home/deployer
          ls -la .kube
          ls -la .config
          mv .kube/config ~/.kube/config
          export HELM_ARGS="--atomic \
            --set less_resources=\"false\" --set production=\"true\" \
            --set certmanager.secret=\"frontend-web-prod-tls\" \
            --set certmanager.issuer=\"letsencrypt-prod\" \
            --set numberReplicas.frontend=2 \
            --set numberReplicas.backend=3"
          sh deploy.sh
